trigger:
- main  # Or the branch you want to trigger the pipeline

pool:
  name: 'default'

variables:
  NODE_ENV: 'production'
  dockerRegistry: 'docker.io/eeba19'  # Replace with your Docker registry
  dockerImageName: 'cicd-backend'
  dockerHubServiceConnection: 'dockerRegistryConnection'  # Your Docker Hub service connection in Azure DevOps

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildDockerImage
    steps:
    - checkout: self  # Checkout the code from the SCM (GitHub repository)

    - task: Docker@2
      inputs:
        command: build
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(dockerRegistry)/$(dockerImageName):$(Build.BuildId)
      displayName: 'Build Docker Image'

    - task: Docker@2
      inputs:
        command: login
        containerRegistry: '$(dockerHubServiceConnection)'
        displayName: 'Login to Docker Registry'

    - task: Docker@2
      inputs:
        command: push
        repository: '$(dockerRegistry)/$(dockerImageName)'
        tags: |
          $(Build.BuildId)
          latest
      displayName: 'Push Docker Image to Registry'
